services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=dev
      - CORS_ORIGINS=http://localhost:5173
      - PUBLIC_BASE_URL=http://localhost:8000
      - EXTERNAL_ENABLED=false
    volumes:
      - backend_uploads:/app/uploads
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
volumes:
  backend_uploads:
