[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "preref-backend"
version = "0.1.0"
dependencies = [
  "fastapi>=0.111.0",
  "uvicorn[standard]>=0.30.0",
  "pydantic>=2.7.0",
  "pydantic-settings>=2.2.1",
  "python-multipart>=0.0.9",
  "httpx>=0.27.0",
  "orjson>=3.10.0"
]

[tool.uvicorn]
factory = true
host = "0.0.0.0"
port = 8000
reload = false
