name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    env:
      UV_PYTHON: '3.12'
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v1
      - name: Install Python 3.12
        run: uv python install 3.12
      - name: Install dependencies
        run: |
          uv pip install -e ./backend ruff pytest
      - name: Lint
        run: uv run ruff check backend
      - name: Format
        run: uv run ruff format --check backend
      - name: Test
        run: uv run pytest -q

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: |
          cd frontend
          bun install
      - name: Clean and build
        run: |
          cd frontend
          bun run clean
          bun vite build
      - name: Verify build
        run: |
          cd frontend
          node scripts/build-verify.mjs
